"""Add UI fields to LeadField

Revision ID: fbaffeed6df7
Revises: a57528fcd5e5
Create Date: 2026-05-28 12:23:13.469778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbaffeed6df7'
down_revision = 'a57528fcd5e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_fields', sa.Column('placeholder', sa.String(), nullable=True))
    op.add_column('lead_fields', sa.Column('section', sa.String(), nullable=True))
    op.add_column('lead_fields', sa.Column('validation', sa.JSON(), nullable=True))
    op.add_column('lead_fields', sa.Column('is_core', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_fields', 'is_core')
    op.drop_column('lead_fields', 'validation')
    op.drop_column('lead_fields', 'section')
    op.drop_column('lead_fields', 'placeholder')
    # ### end Alembic commands ###
